### ISSUE TITLE
SNES(NTSC)/(PAL)/Super Famicom PCB

### ISSUE THREAD

**Issue by pmgducati** [pmgducati/Blue-Retro-AIO-Units#17]
I do not have this system this PCB is compatible with, please put your findings here.

**Comment by amaiorano** [comment]
So far this works perfectly for 2 players, with only 2 level shifters. I wanted it to work for 4 players, but the SNES extensions I got from AliExpress are missing 2 wires -- this is mentioned on [the last bullet point of the official instructions](https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-Cables-Build-Instructions#bill-of-materials-11).

Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/6893883/197601801-9a7b5bbc-1f08-4b02-934b-8624336e8e23.png)

I'm currently waiting on a lot of broken original SFC controllers that I can harvest the cables from so that they have the 7 wires all connected, and will test that multitap support works. I'll report my findings here.

**Comment by pmgducati** [comment]
This is great to hear, looking forward to your updates.

**Comment by RetroBobba** [comment]
I've made a full populated board with resistors for the PAL console and tried Micro Machines with 4 Players. It works fine :-)

Thanks for your work

**Comment by pmgducati** [comment]
Thats Great to hear, thanks for the update!
