### ISSUE TITLE
Sega Genesis/Megadrive Multitap PCB

### ISSUE THREAD

**Issue by pmgducati** [pmgducati/Blue-Retro-AIO-Units#42]
I do not have this system this PCB is compatible with, please put your findings here.

**Comment by DariensArcade** [comment]
Working:  Fully populated Multitap board working in 2 player mode in both 3/6 buttons (BR Setting Gamepad / Gamepad Alt.  respectively) on Genesis Model 1, 2, and 3.  

Further testing needed: I'm getting glitches attempting to use multi-tap modes but probably due to my controllers. i.e. Out of control scrolling with NHL '95 (EA Multi-tap. BR setting "alt")  

Will test further with other controllers/games/tap types

Reporting since no one else has.

**Comment by pmgducati** [comment]
This is great to hear,  is NHL95 the only game you are seeing issues with?  Also is it on an original cart/flashcart?
